# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  client_id: <%= ENV["client_id"] %>
  app_secret: <%= ENV["app_secret"] %>
  db_password: <%= ENV["db_password"] %>

development:
  secret_key_base: 3e41bd3c7c0ac307097268597277cb5e135824f8bd8db6a1c2d9a6bb97d8d8d36b9080c0cfc5b72d1a1f093f2d5d5bc89567bb117b1dc62929d4205f57fc99c7

test:
  secret_key_base: 3637fe834c629ddf58cba10a71b2fd18c611db2765c21bf0f7fcaf1af5f2146190d5ce01c3026c13ee12b21842bfcf9e2f253be3fda12841f0852123609a1d8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>